### ISSUE TITLE
CBlack desktop theme is overriding the fonts, and an easy fix is suggested

### ISSUE THREAD

**Issue by Fifis** [Cloweling/cblack#48]
Cinnamon version: 4.6.6
Distribution: Arch
Installed via: Control Centre → Themes → Add/Remove
How to reproduce: In Cinnamon, opening Control Centre → Themes → Desktop, changing to CBlack.

Desired behaviour: since this issue is not present in the Adapta theme, which is used as an example, look at the ‘Grouped windows’ applet, and one shall observe that it is using the system font (in this case, Arimo).
![adapta-respect](https://user-images.githubusercontent.com/5990916/88193606-23453c00-cc3e-11ea-80fb-31632b9b31a7.png)

Actual behaviour: the CBlack theme is overriding the font with Ubuntu, which ruins the point of having custom system fonts.
![cblack-non-respect](https://user-images.githubusercontent.com/5990916/88194818-8a172500-cc3f-11ea-80e0-db232d23f3dc.png)

Suggested fix:
Changing line 6 in cinnamon/cinnamon.css to
`font-family: sans-serif;`

**Comment by Cloweling** [comment]
Hi @Fifis sorry that until today I realized your suggestion, I have added in version 3.1.1, you can download here https://github.com/Cloweling/cblack/releases and any other suggestions, I am willing to read, thanks.

[Download Theme here](https://github.com/Cloweling/cblack/releases/download/V3.1.1/CBlack.zip)
